port 6379
bind 0.0.0.0
protected-mode no

cluster-enabled yes
cluster-config-file /data/nodes.conf
cluster-node-timeout 3000
cluster-preferred-endpoint-type ip

dir /data
save ""
appendonly no
appendfsync everysec

repl-backlog-size 64mb
repl-diskless-sync yes
repl-diskless-sync-delay 0

maxmemory 512mb
maxmemory-policy allkeys-lru

latency-monitor-threshold 5
loglevel notice
